version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          context: AWS
          account-url: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com'
          repo: 'unifi'
          region: ${AWS_DEFAULT_REGION}
